apiVersion: k8s.f5net.com/v1
kind: F5BnkGateway
metadata:
  name: demo-http2
  namespace: {{.Namespace}}
spec:
  ingressConfig:
    defaultListenerNetworks:
    - name: external
      ipv4BaseCidr: {{.ExternalCIDR}}
      startAddress: {{.VIP}}
      endAddress: {{.VIP}}
      provider: f5-ip-provider
