apiVersion: k8s.f5net.com/v1
kind: F5BnkGateway
metadata:
  name: demo-http2
  namespace: demo-http2
spec:
  ingressConfig:
    defaultListenerNetworks:
    - name: external
      ipv4BaseCidr: 10.0.10.0/24
      startAddress: 10.0.10.111
      endAddress: 10.0.10.111
      provider: f5-ip-provider
