package orchestration

// Hermetic regression for validator Issue 3 round-3 — `LayerAppliedTFVars`
// reads the canonical `terraform.applied.tfvars` snapshot, dedupes
// later-source-wins, drops redacted secret keys, and writes a
// terraform-consumable `.applied-replay.tfvars` next to it.
//
// Round 2 of the Issue 3 fix tried to point terraform directly at the
// canonical snapshot and got bitten in live verify run `20260519-220236`
// by the snapshot's multi-section duplicate keys (terraform: "Each
// argument may be set only once") and by its redacted-secret literal
// overriding `TF_VAR_ibmcloud_api_key`. This test pins the round-3
// contract that closed those gaps. Additive; no pre-existing test
// edited.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jgruberf5/roksbnkctl/internal/config"
)

// realisticSnapshot is the exact on-disk shape PRD 07's writer produces
// for a split-phase trial run that consumed two var-files: the user
// `terraform.tfvars` (sourceLabel: "config.yaml" in PRD 07 wording) AND
// the Sprint 16 round-2 `bnk-phase-override.tfvars`. Both set
// `testing_create_tgw_jumphost` — the exact collision the live verify
// hit. Also exercises the redacted-secret line (`ibmcloud_api_key`).
const realisticSnapshot = `# Generated by roksbnkctl test at 2026-05-19T22:51:10Z after terraform apply on phase=trial.
# Re-generated each apply. Do not edit by hand — your changes will be overwritten.

# === from config.yaml ===
ibmcloud_api_key = "<redacted>"  # source: cred resolver, not persisted
ibmcloud_cluster_region = "ca-tor"
testing_create_tgw_jumphost = true

# === from bnk-phase-override.tfvars ===
create_roks_cluster = false
testing_create_tgw_jumphost = false
use_existing_cluster_vpc = true
`

// TestLayerAppliedTFVars_DedupesAndStripsSecret pins the round-3
// contract: when a canonical snapshot with duplicate keys + a redacted
// secret exists, LayerAppliedTFVars returns the path to a derived
// `.applied-replay.tfvars` that is (a) terraform-consumable
// (single-section, no intra-file dup-key error), (b) later-source-wins
// (the bnk-phase-override value of testing_create_tgw_jumphost beats
// the user-tfvars value), and (c) free of the redacted secret line. The
// exact regression run `20260519-220236` A5 hit — locked here forever.
func TestLayerAppliedTFVars_DedupesAndStripsSecret(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	snapPath, err := config.AppliedTFVarsPath("ws-issue3-r3", "trial")
	if err != nil {
		t.Fatalf("AppliedTFVarsPath: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(snapPath), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(snapPath, []byte(realisticSnapshot), 0o600); err != nil {
		t.Fatalf("write snapshot: %v", err)
	}

	got := LayerAppliedTFVars("ws-issue3-r3", "trial")
	if len(got) != 1 {
		t.Fatalf("LayerAppliedTFVars: got %v, want single-element slice", got)
	}
	replayPath := got[0]
	wantBase := ".applied-replay.tfvars"
	if filepath.Base(replayPath) != wantBase {
		t.Fatalf("replay basename = %q, want %q", filepath.Base(replayPath), wantBase)
	}
	if filepath.Dir(replayPath) != filepath.Dir(snapPath) {
		t.Fatalf("replay dir = %q, want %q (state dir)", filepath.Dir(replayPath), filepath.Dir(snapPath))
	}

	body, err := os.ReadFile(replayPath)
	if err != nil {
		t.Fatalf("read replay: %v", err)
	}
	s := string(body)

	// (c) — redacted secret must be stripped, not echoed.
	if strings.Contains(s, "ibmcloud_api_key") {
		t.Fatalf("replay contains ibmcloud_api_key (must be stripped):\n%s", s)
	}
	if strings.Contains(s, "<redacted>") {
		t.Fatalf("replay contains redacted-token literal:\n%s", s)
	}

	// (b) — later-source-wins: the bnk-phase-override value beats the
	// user-tfvars value. Only the false assignment must remain.
	if !strings.Contains(s, "testing_create_tgw_jumphost = false") {
		t.Fatalf("replay missing later-wins testing_create_tgw_jumphost = false:\n%s", s)
	}
	if strings.Contains(s, "testing_create_tgw_jumphost = true") {
		t.Fatalf("replay still carries the overridden true value (later-wins broken):\n%s", s)
	}

	// (a) — exactly one assignment per key. If terraform would have
	// rejected the canonical snapshot, the replay must not reproduce
	// the duplicate.
	if c := strings.Count(s, "testing_create_tgw_jumphost"); c != 1 {
		t.Fatalf("replay has %d assignments of testing_create_tgw_jumphost, want exactly 1:\n%s", c, s)
	}

	// Sanity: the other keys round-trip.
	for _, want := range []string{
		`ibmcloud_cluster_region = "ca-tor"`,
		`create_roks_cluster = false`,
		`use_existing_cluster_vpc = true`,
	} {
		if !strings.Contains(s, want) {
			t.Fatalf("replay missing %q:\n%s", want, s)
		}
	}
}

// TestLayerAppliedTFVars_AbsentNoOp pins the byte-identical-fallback
// contract: no snapshot → nil → caller behaviour unchanged. Critical
// because the helper is now in the bare-`down -w` hot path; a non-nil
// return here would regress every fresh-workspace lifecycle op.
func TestLayerAppliedTFVars_AbsentNoOp(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	if got := LayerAppliedTFVars("ws-never-applied", "trial"); got != nil {
		t.Fatalf("LayerAppliedTFVars(trial, no-snapshot) = %v, want nil", got)
	}
	if got := LayerAppliedTFVars("ws-never-applied", "cluster"); got != nil {
		t.Fatalf("LayerAppliedTFVars(cluster, no-snapshot) = %v, want nil", got)
	}
}

// TestRequireSnapshotOrVarFile pins the option-(b) gate: a clean
// actionable error replaces terraform's raw "No value for required
// variable" when the caller has no snapshot to replay, no explicit
// --var-file, and no Sprint 19 `init --var-file`-seeded
// `terraform.tfvars.user`. Hermetic — no terraform or filesystem involved.
func TestRequireSnapshotOrVarFile(t *testing.T) {
	t.Run("all three empty → actionable error", func(t *testing.T) {
		err := RequireSnapshotOrVarFile(nil, nil, false, false, "trial", "down")
		if err == nil {
			t.Fatal("expected an error when no snapshot, no --var-file, no user-tfvars, got nil")
		}
		msg := err.Error()
		// Must name the phase + verb + BOTH remedies the operator can
		// copy/paste. These substrings are the user-facing contract.
		for _, want := range []string{
			"trial phase",
			"roksbnkctl down -w <workspace>",
			"--var-file",
			"`roksbnkctl up --var-file <path>`",
			"roksbnkctl init --var-file <path> -w <workspace>",
		} {
			if !strings.Contains(msg, want) {
				t.Fatalf("error message missing %q:\n%s", want, msg)
			}
		}
	})

	t.Run("snapshot present → no-op", func(t *testing.T) {
		// A non-empty replayed slice means LayerAppliedTFVars found a
		// snapshot; the gate must NOT refuse — the round-3 replay
		// covers it.
		err := RequireSnapshotOrVarFile([]string{"/some/.applied-replay.tfvars"}, nil, false, false, "trial", "down")
		if err != nil {
			t.Fatalf("expected nil when snapshot exists, got: %v", err)
		}
	})

	t.Run("user --var-file present → no-op", func(t *testing.T) {
		// Operator supplied inputs explicitly; the gate must NOT refuse.
		err := RequireSnapshotOrVarFile(nil, []string{"/path/to/terraform.tfvars"}, false, false, "trial", "down")
		if err != nil {
			t.Fatalf("expected nil when user --var-file present, got: %v", err)
		}
	})

	t.Run("workspace-persistent user-tfvars present → no-op", func(t *testing.T) {
		// Sprint 19 path: `init --var-file` seeded `terraform.tfvars.user`;
		// the lifecycle layers it automatically via tf.Workspace.varFiles.
		// The gate must NOT refuse on bare `-w <ws>` against such a
		// workspace — that is the whole point of the feature.
		err := RequireSnapshotOrVarFile(nil, nil, true, false, "trial", "plan")
		if err != nil {
			t.Fatalf("expected nil when init --var-file seeded terraform.tfvars.user, got: %v", err)
		}
	})

	t.Run("config.yaml renders complete (prefix workspace) → no-op", func(t *testing.T) {
		// Sprint 27: a Sprint 26 prefix-driven workspace renders a complete
		// tfvars from config.yaml (+ api_key via env), so it is self-sufficient
		// even with no snapshot / no --var-file / no terraform.tfvars.user.
		// This is the path that lets a prefix workspace whose first `up`
		// failed still be `down`'d.
		err := RequireSnapshotOrVarFile(nil, nil, false, true, "trial", "down")
		if err != nil {
			t.Fatalf("expected nil when config.yaml renders a complete tfvars, got: %v", err)
		}
	})

	t.Run("all four present → no-op", func(t *testing.T) {
		err := RequireSnapshotOrVarFile(
			[]string{"/some/.applied-replay.tfvars"},
			[]string{"/path/to/terraform.tfvars"},
			true,
			true,
			"cluster", "cluster down",
		)
		if err != nil {
			t.Fatalf("expected nil when all four present, got: %v", err)
		}
	})

	t.Run("phase + verb shape the message", func(t *testing.T) {
		// The error names BOTH the phase and the verb so the user can
		// copy/paste the exact command. Pin both substring shapes.
		err := RequireSnapshotOrVarFile(nil, nil, false, false, "cluster", "cluster down")
		if err == nil {
			t.Fatal("expected an error, got nil")
		}
		msg := err.Error()
		for _, want := range []string{
			"cluster phase",
			"roksbnkctl cluster down -w <workspace>",
		} {
			if !strings.Contains(msg, want) {
				t.Fatalf("error message missing %q:\n%s", want, msg)
			}
		}
	})
}

// TestLayerAppliedTFVars_ClusterPhase pins phase routing — the cluster
// phase's snapshot lives in WorkspaceClusterStateDir, the trial phase's
// in WorkspaceStateDir. The replay file must be written next to the
// snapshot it derives from, not in a shared location.
func TestLayerAppliedTFVars_ClusterPhase(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	snapPath, err := config.AppliedTFVarsPath("ws-issue3-r3", "cluster")
	if err != nil {
		t.Fatalf("AppliedTFVarsPath(cluster): %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(snapPath), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(snapPath, []byte(realisticSnapshot), 0o600); err != nil {
		t.Fatalf("write snapshot: %v", err)
	}

	got := LayerAppliedTFVars("ws-issue3-r3", "cluster")
	if len(got) != 1 {
		t.Fatalf("LayerAppliedTFVars(cluster): got %v, want single-element slice", got)
	}
	if filepath.Dir(got[0]) != filepath.Dir(snapPath) {
		t.Fatalf("replay dir = %q, want cluster state dir %q", filepath.Dir(got[0]), filepath.Dir(snapPath))
	}
	// Trial phase has no snapshot in this ws — must stay nil (proves
	// phase routing is real, not a wildcard).
	if g := LayerAppliedTFVars("ws-issue3-r3", "trial"); g != nil {
		t.Fatalf("LayerAppliedTFVars(trial, no-snapshot) = %v, want nil", g)
	}
}

// #219 — END TO END, against the file the reporter actually had on disk.
//
// The unit tests cover the parser; this covers the thing that broke: the replay
// file handed to `terraform destroy`. It asserts on the bytes written, because
// the failure was a parse error in exactly those bytes.
func TestReplayFileFromACorruptSnapshotIsParseable(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	snapPath, err := config.AppliedTFVarsPath("bnk-test1", "trial")
	if err != nil {
		t.Fatalf("AppliedTFVarsPath: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(snapPath), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	// Written by a build that predates multi-line value support. The snapshot is
	// only rewritten on apply, so `bnk down` regenerated the same broken replay
	// every time and the workspace could not be destroyed.
	corrupt := `# Generated by roksbnkctl
cneinstance_cluster_name = "bnk-test1"
cneinstance_network_zones = [
cneinstance_tmm_k8s_routes = "172.17.0.0/18,172.21.0.0/16,192.168.100.0/24"
prefix = "bnk-test1"
`
	if err := os.WriteFile(snapPath, []byte(corrupt), 0o600); err != nil {
		t.Fatalf("write snapshot: %v", err)
	}

	got := LayerAppliedTFVars("bnk-test1", "trial")
	if len(got) != 1 {
		t.Fatalf("LayerAppliedTFVars = %v, want one replay file", got)
	}
	body, err := os.ReadFile(got[0])
	if err != nil {
		t.Fatalf("read replay: %v", err)
	}
	s := string(body)

	// The exact failure: a bare `[` as a value.
	for _, line := range strings.Split(s, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") || trimmed == "" {
			continue
		}
		if strings.HasSuffix(trimmed, "= [") || strings.HasSuffix(trimmed, "= {") {
			t.Errorf("the replay still emits a bare block opener:\n  %s\n"+
				"terraform rejects this with `Missing item separator` and the workspace "+
				"cannot be destroyed (#219). Full file:\n%s", trimmed, s)
		}
	}

	// Every assignment that followed the bad block must still be there — the
	// silent half of the defect.
	for _, want := range []string{"cneinstance_tmm_k8s_routes", "prefix", "cneinstance_cluster_name"} {
		if !strings.Contains(s, want) {
			t.Errorf("%q is missing from the replay: it was swallowed by the unterminated "+
				"block, so the destroy would run with less than the apply used.\n%s", want, s)
		}
	}
}

// A well-formed multizone snapshot must still round-trip through the replay
// intact. Multizone is the only shape this tool deploys, so a guard that drops
// good zone lists would be worse than the bug.
func TestReplayKeepsAWellFormedZoneList(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	snapPath, err := config.AppliedTFVarsPath("bnk-ok", "trial")
	if err != nil {
		t.Fatalf("AppliedTFVarsPath: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(snapPath), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	good := `prefix = "bnk-ok"
cneinstance_network_zones = [
  {
    ext_vlan_cidr   = "10.243.1.0/24"
    internal_selfip = "10.243.2.10"
  },
  {
    ext_vlan_cidr   = "10.243.3.0/24"
    internal_selfip = "10.243.4.10"
  },
]
`
	if err := os.WriteFile(snapPath, []byte(good), 0o600); err != nil {
		t.Fatalf("write snapshot: %v", err)
	}
	got := LayerAppliedTFVars("bnk-ok", "trial")
	if len(got) != 1 {
		t.Fatalf("LayerAppliedTFVars = %v", got)
	}
	body, _ := os.ReadFile(got[0])
	s := string(body)
	for _, want := range []string{"10.243.1.0/24", "10.243.3.0/24", "]"} {
		if !strings.Contains(s, want) {
			t.Errorf("the zone list did not survive the replay (missing %q):\n%s", want, s)
		}
	}
	if strings.Contains(s, "<skipped:") {
		t.Errorf("a well-formed zone list was skipped as unbalanced:\n%s", s)
	}
}

// The writer's balance check is defence in depth, and defence in depth still
// needs a test: with the parser fixed the writer never sees an unbalanced value
// through the normal path, so removing the guard passed the whole suite. This
// drives writeAppliedReplayFile directly.
//
// It matters because the parser is not the only way a value reaches this map —
// a snapshot corrupt in some shape nobody has thought of yet still ends up here,
// and on `down` an unparseable var-file is a workspace nobody can destroy.
func TestTheReplayWriterRefusesToEmitUnbalancedValues(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".applied-replay.tfvars")
	err := writeAppliedReplayFile(path, "trial", map[string]string{
		"good_scalar": `"kept"`,
		"good_block":  "[\n  { a = \"b\" },\n]",
		"bad_open":    "[",
		"bad_close":   "]",
	})
	if err != nil {
		t.Fatalf("write: %v", err)
	}
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	s := string(body)

	for _, bad := range []string{"bad_open = [", "bad_close = ]"} {
		if strings.Contains(s, bad) {
			t.Errorf("emitted %q — terraform cannot parse it and the destroy dies (#219):\n%s", bad, s)
		}
	}
	// Skipped keys are NAMED, not silently dropped: an operator debugging a
	// missing variable has to be able to see it was skipped and why.
	for _, want := range []string{"# bad_open =", "# bad_close ="} {
		if !strings.Contains(s, want) {
			t.Errorf("skipped a key without saying so (%q missing):\n%s", want, s)
		}
	}
	if !strings.Contains(s, `good_scalar = "kept"`) {
		t.Errorf("a balanced scalar was dropped:\n%s", s)
	}
	if !strings.Contains(s, "good_block = [") || !strings.Contains(s, "]") {
		t.Errorf("a balanced multi-line block was dropped:\n%s", s)
	}
}
