package orchestration

// Hermetic regression for validator Issue 3 round-3 — `LayerAppliedTFVars`
// reads the canonical `terraform.applied.tfvars` snapshot, dedupes
// later-source-wins, drops redacted secret keys, and writes a
// terraform-consumable `.applied-replay.tfvars` next to it.
//
// Round 2 of the Issue 3 fix tried to point terraform directly at the
// canonical snapshot and got bitten in live verify run `20260519-220236`
// by the snapshot's multi-section duplicate keys (terraform: "Each
// argument may be set only once") and by its redacted-secret literal
// overriding `TF_VAR_ibmcloud_api_key`. This test pins the round-3
// contract that closed those gaps. Additive; no pre-existing test
// edited.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jgruberf5/roksbnkctl/internal/config"
)

// realisticSnapshot is the exact on-disk shape PRD 07's writer produces
// for a split-phase trial run that consumed two var-files: the user
// `terraform.tfvars` (sourceLabel: "config.yaml" in PRD 07 wording) AND
// the Sprint 16 round-2 `bnk-phase-override.tfvars`. Both set
// `testing_create_tgw_jumphost` — the exact collision the live verify
// hit. Also exercises the redacted-secret line (`ibmcloud_api_key`).
const realisticSnapshot = `# Generated by roksbnkctl test at 2026-05-19T22:51:10Z after terraform apply on phase=trial.
# Re-generated each apply. Do not edit by hand — your changes will be overwritten.

# === from config.yaml ===
ibmcloud_api_key = "<redacted>"  # source: cred resolver, not persisted
ibmcloud_cluster_region = "ca-tor"
testing_create_tgw_jumphost = true

# === from bnk-phase-override.tfvars ===
create_roks_cluster = false
testing_create_tgw_jumphost = false
use_existing_cluster_vpc = true
`

// TestLayerAppliedTFVars_DedupesAndStripsSecret pins the round-3
// contract: when a canonical snapshot with duplicate keys + a redacted
// secret exists, LayerAppliedTFVars returns the path to a derived
// `.applied-replay.tfvars` that is (a) terraform-consumable
// (single-section, no intra-file dup-key error), (b) later-source-wins
// (the bnk-phase-override value of testing_create_tgw_jumphost beats
// the user-tfvars value), and (c) free of the redacted secret line. The
// exact regression run `20260519-220236` A5 hit — locked here forever.
func TestLayerAppliedTFVars_DedupesAndStripsSecret(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	snapPath, err := config.AppliedTFVarsPath("ws-issue3-r3", "trial")
	if err != nil {
		t.Fatalf("AppliedTFVarsPath: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(snapPath), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(snapPath, []byte(realisticSnapshot), 0o600); err != nil {
		t.Fatalf("write snapshot: %v", err)
	}

	got := LayerAppliedTFVars("ws-issue3-r3", "trial")
	if len(got) != 1 {
		t.Fatalf("LayerAppliedTFVars: got %v, want single-element slice", got)
	}
	replayPath := got[0]
	wantBase := ".applied-replay.tfvars"
	if filepath.Base(replayPath) != wantBase {
		t.Fatalf("replay basename = %q, want %q", filepath.Base(replayPath), wantBase)
	}
	if filepath.Dir(replayPath) != filepath.Dir(snapPath) {
		t.Fatalf("replay dir = %q, want %q (state dir)", filepath.Dir(replayPath), filepath.Dir(snapPath))
	}

	body, err := os.ReadFile(replayPath)
	if err != nil {
		t.Fatalf("read replay: %v", err)
	}
	s := string(body)

	// (c) — redacted secret must be stripped, not echoed.
	if strings.Contains(s, "ibmcloud_api_key") {
		t.Fatalf("replay contains ibmcloud_api_key (must be stripped):\n%s", s)
	}
	if strings.Contains(s, "<redacted>") {
		t.Fatalf("replay contains redacted-token literal:\n%s", s)
	}

	// (b) — later-source-wins: the bnk-phase-override value beats the
	// user-tfvars value. Only the false assignment must remain.
	if !strings.Contains(s, "testing_create_tgw_jumphost = false") {
		t.Fatalf("replay missing later-wins testing_create_tgw_jumphost = false:\n%s", s)
	}
	if strings.Contains(s, "testing_create_tgw_jumphost = true") {
		t.Fatalf("replay still carries the overridden true value (later-wins broken):\n%s", s)
	}

	// (a) — exactly one assignment per key. If terraform would have
	// rejected the canonical snapshot, the replay must not reproduce
	// the duplicate.
	if c := strings.Count(s, "testing_create_tgw_jumphost"); c != 1 {
		t.Fatalf("replay has %d assignments of testing_create_tgw_jumphost, want exactly 1:\n%s", c, s)
	}

	// Sanity: the other keys round-trip.
	for _, want := range []string{
		`ibmcloud_cluster_region = "ca-tor"`,
		`create_roks_cluster = false`,
		`use_existing_cluster_vpc = true`,
	} {
		if !strings.Contains(s, want) {
			t.Fatalf("replay missing %q:\n%s", want, s)
		}
	}
}

// TestLayerAppliedTFVars_AbsentNoOp pins the byte-identical-fallback
// contract: no snapshot → nil → caller behaviour unchanged. Critical
// because the helper is now in the bare-`down -w` hot path; a non-nil
// return here would regress every fresh-workspace lifecycle op.
func TestLayerAppliedTFVars_AbsentNoOp(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	if got := LayerAppliedTFVars("ws-never-applied", "trial"); got != nil {
		t.Fatalf("LayerAppliedTFVars(trial, no-snapshot) = %v, want nil", got)
	}
	if got := LayerAppliedTFVars("ws-never-applied", "cluster"); got != nil {
		t.Fatalf("LayerAppliedTFVars(cluster, no-snapshot) = %v, want nil", got)
	}
}

// TestLayerAppliedTFVars_ClusterPhase pins phase routing — the cluster
// phase's snapshot lives in WorkspaceClusterStateDir, the trial phase's
// in WorkspaceStateDir. The replay file must be written next to the
// snapshot it derives from, not in a shared location.
func TestLayerAppliedTFVars_ClusterPhase(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	snapPath, err := config.AppliedTFVarsPath("ws-issue3-r3", "cluster")
	if err != nil {
		t.Fatalf("AppliedTFVarsPath(cluster): %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(snapPath), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(snapPath, []byte(realisticSnapshot), 0o600); err != nil {
		t.Fatalf("write snapshot: %v", err)
	}

	got := LayerAppliedTFVars("ws-issue3-r3", "cluster")
	if len(got) != 1 {
		t.Fatalf("LayerAppliedTFVars(cluster): got %v, want single-element slice", got)
	}
	if filepath.Dir(got[0]) != filepath.Dir(snapPath) {
		t.Fatalf("replay dir = %q, want cluster state dir %q", filepath.Dir(got[0]), filepath.Dir(snapPath))
	}
	// Trial phase has no snapshot in this ws — must stay nil (proves
	// phase routing is real, not a wildcard).
	if g := LayerAppliedTFVars("ws-issue3-r3", "trial"); g != nil {
		t.Fatalf("LayerAppliedTFVars(trial, no-snapshot) = %v, want nil", g)
	}
}
