package main

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// TestRun_SmokeOutput end-to-end verifies the generator emits a
// well-formed chapter for the LIVE terraform/variables.tf tree. Runs
// the generator with the repo root as cwd and asserts:
//
//   - the chapter starts with the expected H1
//   - the auto-generation note is present
//   - a known root-module variable (ibmcloud_api_key) renders
//   - a known module section (roks_cluster) renders
//   - the sensitive-flag column is honoured for ibmcloud_api_key
//   - markdown tables are balanced (every `| Variable |` header has a
//     `|---|---|---|---|---|` separator on the next line)
func TestRun_SmokeOutput(t *testing.T) {
	// The generator reads from `terraform/variables.tf` relative to cwd
	// so the test has to run from the repo root.
	repoRoot, err := findRepoRoot()
	if err != nil {
		t.Skipf("can't locate repo root: %v", err)
	}
	t.Chdir(repoRoot)

	var buf bytes.Buffer
	if err := run(&buf); err != nil {
		t.Fatalf("run: %v", err)
	}
	out := buf.String()

	if !strings.HasPrefix(out, "# Terraform variable reference\n") {
		t.Fatalf("output does not start with `# Terraform variable reference` header; got:\n%s", firstLines(out, 5))
	}
	if !strings.Contains(out, "Auto-generated by `go run ./tools/refgen/tfvars-md") {
		t.Errorf("output missing auto-generation note")
	}
	if !strings.Contains(out, "## Root module variables") {
		t.Errorf("output missing `## Root module variables` section")
	}
	if !strings.Contains(out, "| `ibmcloud_api_key` |") {
		t.Errorf("output missing ibmcloud_api_key row; got first 40 lines:\n%s", firstLines(out, 40))
	}
	if !strings.Contains(out, "## Module: `roks_cluster`") {
		t.Errorf("output missing `## Module: roks_cluster` section")
	}

	// The ibmcloud_api_key variable has `sensitive = true` in the HCL;
	// its row must reflect that via the **yes** marker.
	apiKeyRowRe := regexp.MustCompile(`\|\s*` + "`" + `ibmcloud_api_key` + "`" + `\s*\|[^|]+\|[^|]+\|[^|]+\|\s*\*\*yes\*\*\s*\|`)
	if !apiKeyRowRe.MatchString(out) {
		t.Errorf("ibmcloud_api_key row should be flagged sensitive (**yes**); got line:\n%s",
			grepLines(out, "ibmcloud_api_key"))
	}

	// Markdown table sanity: every "| Variable |" header is followed by
	// the expected separator.
	lines := strings.Split(out, "\n")
	for i, ln := range lines {
		if !strings.HasPrefix(ln, "| Variable |") {
			continue
		}
		if i+1 >= len(lines) {
			t.Errorf("variable-table header at line %d has no separator (EOF)", i+1)
			continue
		}
		sep := lines[i+1]
		if !strings.HasPrefix(sep, "|---") {
			t.Errorf("variable-table at line %d missing separator row; got %q", i+1, sep)
		}
	}
}

// TestParseFile_BasicShape verifies the regex-driven HCL parser
// correctly extracts the common attribute shapes from a synthetic
// variables.tf fixture: required (no default), defaulted-string,
// defaulted-bool, defaulted-list, sensitive=true, multi-line
// description.
func TestParseFile_BasicShape(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "variables.tf")
	content := `
variable "required_one" {
  description = "no default; required input"
  type        = string
  sensitive   = true
}

variable "defaulted_string" {
  description = "with default"
  type        = string
  default     = "hello"
}

variable "defaulted_bool" {
  description = "bool"
  type        = bool
  default     = true
}

variable "defaulted_list" {
  description = "list of strings"
  type        = list(string)
  default     = ["a", "b", "c"]
}

variable "nested_block" {
  description = "with a nested validation"
  type        = string
  default     = "x"

  validation {
    condition     = length(var.nested_block) > 0
    error_message = "must not be empty"
  }
}
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("writing fixture: %v", err)
	}
	vars, err := parseFile(path)
	if err != nil {
		t.Fatalf("parseFile: %v", err)
	}
	if len(vars) != 5 {
		t.Fatalf("expected 5 variables, got %d", len(vars))
	}

	want := map[string]struct {
		typ, def    string
		sensitive   bool
		description string
	}{
		"required_one":     {typ: "string", def: "", sensitive: true, description: "no default; required input"},
		"defaulted_string": {typ: "string", def: `"hello"`, sensitive: false, description: "with default"},
		"defaulted_bool":   {typ: "bool", def: "true", sensitive: false, description: "bool"},
		"defaulted_list":   {typ: "list(string)", def: `["a", "b", "c"]`, sensitive: false, description: "list of strings"},
		"nested_block":     {typ: "string", def: `"x"`, sensitive: false, description: "with a nested validation"},
	}
	for _, v := range vars {
		w, ok := want[v.Name]
		if !ok {
			t.Errorf("unexpected variable %q", v.Name)
			continue
		}
		if v.Type != w.typ {
			t.Errorf("%s: type = %q, want %q", v.Name, v.Type, w.typ)
		}
		if v.Default != w.def {
			t.Errorf("%s: default = %q, want %q", v.Name, v.Default, w.def)
		}
		if v.Sensitive != w.sensitive {
			t.Errorf("%s: sensitive = %v, want %v", v.Name, v.Sensitive, w.sensitive)
		}
		if v.Description != w.description {
			t.Errorf("%s: description = %q, want %q", v.Name, v.Description, w.description)
		}
	}
}

// TestFindMatchingBrace covers the brace-balance scanner used by the
// HCL parser. Strings containing `{` / `}` must NOT throw off the
// depth count.
func TestFindMatchingBrace(t *testing.T) {
	tests := []struct {
		name string
		in   string
		open int
		want int
	}{
		{"empty body", "{}", 0, 1},
		{"single char inside", "{a}", 0, 2},
		{"nested", "{a{b}c}", 0, 6},
		{"string with braces", `{a = "{}"}`, 0, 9},
		{"unbalanced returns -1", "{a", 0, -1},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := findMatchingBrace(tc.in, tc.open); got != tc.want {
				t.Errorf("findMatchingBrace(%q, %d) = %d, want %d", tc.in, tc.open, got, tc.want)
			}
		})
	}
}

func findRepoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			// Confirm it's the roksbnkctl repo by looking for
			// terraform/variables.tf.
			if _, err := os.Stat(filepath.Join(dir, "terraform", "variables.tf")); err == nil {
				return dir, nil
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", os.ErrNotExist
		}
		dir = parent
	}
}

func firstLines(s string, n int) string {
	parts := strings.SplitN(s, "\n", n+1)
	if len(parts) > n {
		parts = parts[:n]
	}
	return strings.Join(parts, "\n")
}

func grepLines(s, substr string) string {
	var b strings.Builder
	for _, ln := range strings.Split(s, "\n") {
		if strings.Contains(ln, substr) {
			b.WriteString(ln)
			b.WriteByte('\n')
		}
	}
	return b.String()
}
