apiVersion: v1
clusters:
- cluster:
    server: https://c116-e.us-south.containers.cloud.ibm.com:30305
  name: tf-roks-cluster-t1-0833/d7s5kvbd00hh9bknaieg
- cluster:
    server: https://c116-e.us-south.containers.cloud.ibm.com:30305
  name: c116-e-us-south-containers-cloud-ibm-com:30305
contexts:
- context:
    cluster: tf-roks-cluster-t1-0833/d7s5kvbd00hh9bknaieg
    namespace: default
    user: ""
  name: tf-roks-cluster-t1-0833/d7s5kvbd00hh9bknaieg
- context:
    cluster: c116-e-us-south-containers-cloud-ibm-com:30305
    namespace: default
    user: IAM#j.gruber@f5.com/c116-e-us-south-containers-cloud-ibm-com:30305
  name: default/c116-e-us-south-containers-cloud-ibm-com:30305/IAM#j.gruber@f5.com
current-context: default/c116-e-us-south-containers-cloud-ibm-com:30305/IAM#j.gruber@f5.com
kind: Config
users:
- name: IAM#j.gruber@f5.com/c116-e-us-south-containers-cloud-ibm-com:30305
  user:
    token: sha256~fPhr4k7Z8tCE6P8pQI_g9M54JSDXhqSJhoNq7G8dr2Y
