apiVersion: v1
clusters:
- cluster:
    server: https://c100-e.us-south.containers.cloud.ibm.com:30785
  name: tf-roks-cluster-s2343/d7sjom2d01fhu0uvi5rg
- cluster:
    server: https://c100-e.us-south.containers.cloud.ibm.com:30785
  name: c100-e-us-south-containers-cloud-ibm-com:30785
contexts:
- context:
    cluster: tf-roks-cluster-s2343/d7sjom2d01fhu0uvi5rg
    namespace: default
    user: ""
  name: tf-roks-cluster-s2343/d7sjom2d01fhu0uvi5rg
- context:
    cluster: c100-e-us-south-containers-cloud-ibm-com:30785
    namespace: default
    user: IAM#j.gruber@f5.com/c100-e-us-south-containers-cloud-ibm-com:30785
  name: default/c100-e-us-south-containers-cloud-ibm-com:30785/IAM#j.gruber@f5.com
current-context: default/c100-e-us-south-containers-cloud-ibm-com:30785/IAM#j.gruber@f5.com
kind: Config
users:
- name: IAM#j.gruber@f5.com/c100-e-us-south-containers-cloud-ibm-com:30785
  user:
    token: sha256~aHgIfPgeItRZhAGupi9liHIIwnc5Nkr6ZAbmhd7Ny2I
