apiVersion: gateway.k8s.f5net.com/v1
kind: L4Route
metadata:
  name: diameter-l4route
  namespace: {{.Namespace}}
spec:
  parentRefs:
  - name: diameter-gateway
    sectionName: diameter-listener
  protocol: TCP
  pvaAccelerationMode: disabled
  rules:
  - backendRefs:
    - name: diameter-responder
      port: 3868
