package tf

import (
	"strings"
	"testing"

	"github.com/jgruberf5/roksbnkctl/internal/config"
)

func TestBackendOverrideHCL_LocalDefault(t *testing.T) {
	// Absent state block and explicit "local" both render the same local
	// backend, byte-identical to pre-PRD-16.
	want := `# Generated by roksbnkctl. Do not edit by hand.
# Pins terraform's local backend to the workspace state dir, so plan/
# apply/destroy don't need the deprecated -state= flag.
terraform {
  backend "local" {
    path = "/ws/state/terraform.tfstate"
  }
}
`
	for _, st := range []config.StateCfg{{}, {Backend: "local"}} {
		body, useS3, err := backendOverrideHCL(st, "ws", "/ws/state")
		if err != nil {
			t.Fatalf("backendOverrideHCL(%+v): %v", st, err)
		}
		if useS3 {
			t.Errorf("local backend should not set useS3")
		}
		if body != want {
			t.Errorf("local body mismatch:\n got: %q\nwant: %q", body, want)
		}
	}
}

func TestBackendOverrideHCL_S3(t *testing.T) {
	st := config.StateCfg{
		Backend: "s3",
		S3: &config.StateS3Cfg{
			Endpoint: "https://s3.us-south.cloud-object-storage.appdomain.cloud",
			Bucket:   "acme-tfstate",
			Region:   "us-south",
		},
	}
	body, useS3, err := backendOverrideHCL(st, "ws", "/home/u/.roksbnkctl/ws/state-cluster")
	if err != nil {
		t.Fatalf("backendOverrideHCL: %v", err)
	}
	if !useS3 {
		t.Fatal("s3 backend should set useS3")
	}
	for _, want := range []string{
		`backend "s3"`,
		`endpoints = { s3 = "https://s3.us-south.cloud-object-storage.appdomain.cloud" }`,
		`bucket    = "acme-tfstate"`,
		`key       = "ws/ws/cluster/terraform.tfstate"`, // default prefix = workspace, per-phase
		`region    = "us-south"`,
		`use_lockfile = true`,
		`skip_s3_checksum            = true`,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("s3 body missing %q:\n%s", want, body)
		}
	}
}

func TestBackendOverrideHCL_S3_KeyPrefixAndPhases(t *testing.T) {
	st := config.StateCfg{Backend: "s3", S3: &config.StateS3Cfg{
		Endpoint: "https://e", Bucket: "b", Region: "r", KeyPrefix: "team-a",
	}}
	cases := map[string]string{
		"/x/state":         "team-a/ws/bnk/terraform.tfstate",
		"/x/state-cluster": "team-a/ws/cluster/terraform.tfstate",
		"/x/state-testing": "team-a/ws/testing/terraform.tfstate",
		"/x/state-gateway": "team-a/ws/gateway/terraform.tfstate",
	}
	for dir, wantKey := range cases {
		body, _, err := backendOverrideHCL(st, "ws", dir)
		if err != nil {
			t.Fatalf("%s: %v", dir, err)
		}
		if !strings.Contains(body, `key       = "`+wantKey+`"`) {
			t.Errorf("%s → key not %q:\n%s", dir, wantKey, body)
		}
	}
}

func TestBackendOverrideHCL_Errors(t *testing.T) {
	if _, _, err := backendOverrideHCL(config.StateCfg{Backend: "s3"}, "ws", "/x/state"); err == nil {
		t.Error("s3 without s3 block should error")
	}
	if _, _, err := backendOverrideHCL(config.StateCfg{Backend: "s3", S3: &config.StateS3Cfg{Bucket: "b", Region: "r"}}, "ws", "/x/state"); err == nil {
		t.Error("s3 missing endpoint should error")
	}
	if _, _, err := backendOverrideHCL(config.StateCfg{Backend: "bogus"}, "ws", "/x/state"); err == nil {
		t.Error("unknown backend should error")
	}
}

func TestTfVersionAtLeast(t *testing.T) {
	cases := []struct {
		have string
		ok   bool
	}{
		{"1.10.5", true}, {"1.10.0", true}, {"1.11.0", true}, {"2.0.0", true},
		{"1.9.8", false}, {"1.5.7", false}, {"0.15.0", false}, {"garbage", false},
	}
	for _, c := range cases {
		if got := tfVersionAtLeast(c.have, 1, 10); got != c.ok {
			t.Errorf("tfVersionAtLeast(%q, 1, 10) = %v, want %v", c.have, got, c.ok)
		}
	}
}

func TestResolveCOSHMAC(t *testing.T) {
	// Default sources read the roksbnkctl-specific vars.
	t.Run("default vars", func(t *testing.T) {
		t.Setenv("ROKSBNKCTL_COS_HMAC_ACCESS_KEY", "AK")
		t.Setenv("ROKSBNKCTL_COS_HMAC_SECRET_KEY", "SK")
		a, s, err := resolveCOSHMAC(&config.StateS3Cfg{})
		if err != nil || a != "AK" || s != "SK" {
			t.Fatalf("got (%q,%q,%v)", a, s, err)
		}
	})
	// With default sources unset, fall back to the standard AWS_* vars.
	t.Run("aws fallback", func(t *testing.T) {
		t.Setenv("ROKSBNKCTL_COS_HMAC_ACCESS_KEY", "")
		t.Setenv("ROKSBNKCTL_COS_HMAC_SECRET_KEY", "")
		t.Setenv("AWS_ACCESS_KEY_ID", "awsA")
		t.Setenv("AWS_SECRET_ACCESS_KEY", "awsS")
		a, s, err := resolveCOSHMAC(&config.StateS3Cfg{})
		if err != nil || a != "awsA" || s != "awsS" {
			t.Fatalf("got (%q,%q,%v)", a, s, err)
		}
	})
	// A named source reads exactly that var (no AWS fallback).
	t.Run("named source", func(t *testing.T) {
		t.Setenv("MY_AK", "x")
		t.Setenv("MY_SK", "y")
		t.Setenv("AWS_ACCESS_KEY_ID", "shouldNotUse")
		a, s, err := resolveCOSHMAC(&config.StateS3Cfg{AccessKeySource: "MY_AK", SecretKeySource: "MY_SK"})
		if err != nil || a != "x" || s != "y" {
			t.Fatalf("got (%q,%q,%v)", a, s, err)
		}
	})
	// Missing keys → actionable error.
	t.Run("missing", func(t *testing.T) {
		t.Setenv("ROKSBNKCTL_COS_HMAC_ACCESS_KEY", "")
		t.Setenv("ROKSBNKCTL_COS_HMAC_SECRET_KEY", "")
		t.Setenv("AWS_ACCESS_KEY_ID", "")
		t.Setenv("AWS_SECRET_ACCESS_KEY", "")
		if _, _, err := resolveCOSHMAC(&config.StateS3Cfg{}); err == nil {
			t.Error("expected error when HMAC keys absent")
		}
	})
}
