package tf

// PRD 16 — terraform backend selection. roksbnkctl writes a
// `roksbnkctl_backend_override.tf` per phase pinning where state lives.
// Default is the local backend (the original behaviour); an
// opt-in `state.backend: s3` block routes each phase's state into an
// S3-compatible bucket (IBM COS) with native lockfile locking.

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"

	"github.com/jgruberf5/roksbnkctl/internal/config"
)

// backendOverrideHCL renders the backend override for one phase. Returns
// the HCL body, whether the s3 backend was selected (so the caller does
// the version preflight + HMAC env injection), and any config error.
//
// The local body is intentionally identical to the pre-PRD-16 inline
// string so existing workspaces render unchanged.
func backendOverrideHCL(st config.StateCfg, workspace, stateDir string) (body string, useS3 bool, err error) {
	switch st.Backend {
	case "", "local":
		return fmt.Sprintf(`# Generated by roksbnkctl. Do not edit by hand.
# Pins terraform's local backend to the workspace state dir, so plan/
# apply/destroy don't need the deprecated -state= flag.
terraform {
  backend "local" {
    path = %q
  }
}
`, filepath.Join(stateDir, "terraform.tfstate")), false, nil

	case "s3":
		s3 := st.S3
		if s3 == nil || s3.Endpoint == "" || s3.Bucket == "" || s3.Region == "" {
			return "", false, fmt.Errorf("state.backend = \"s3\" requires state.s3.{endpoint, bucket, region}")
		}
		key := s3StateKey(s3, workspace, stateDir)
		return fmt.Sprintf(`# Generated by roksbnkctl. Do not edit by hand.
# COS/S3 remote backend (PRD 16). HMAC creds are injected as AWS_* env to
# the terraform child — never written here or into the state object.
terraform {
  backend "s3" {
    endpoints = { s3 = %q }
    bucket    = %q
    key       = %q
    region    = %q

    skip_credentials_validation = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true
    skip_s3_checksum            = true
    use_path_style              = true

    use_lockfile = true
  }
}
`, s3.Endpoint, s3.Bucket, key, s3.Region), true, nil

	default:
		return "", false, fmt.Errorf("unknown state.backend %q (want \"local\" or \"s3\")", st.Backend)
	}
}

// s3StateKey computes the per-phase S3 object key. path.Join (not
// filepath) — S3 keys use forward slashes on every OS. One key per phase
// so the four phases share a bucket without colliding.
func s3StateKey(s3 *config.StateS3Cfg, workspace, stateDir string) string {
	prefix := s3.KeyPrefix
	if prefix == "" {
		prefix = workspace
	}
	return path.Join(prefix, workspace, phaseFromStateDir(stateDir), "terraform.tfstate")
}

// S3StateKey is the exported per-phase key, for the `state migrate` path's
// remote-key clobber check. Errors unless st is an s3 backend.
func S3StateKey(st config.StateCfg, workspace, stateDir string) (string, error) {
	if st.Backend != "s3" || st.S3 == nil {
		return "", fmt.Errorf("state.backend is not \"s3\"")
	}
	return s3StateKey(st.S3, workspace, stateDir), nil
}

// ResolveCOSHMAC exposes the env-first HMAC resolution to the CLI (the
// migrate command needs the keys for the remote-key HEAD check; Open
// re-resolves them for the terraform env).
func ResolveCOSHMAC(s3 *config.StateS3Cfg) (access, secret string, err error) {
	return resolveCOSHMAC(s3)
}

// phaseFromStateDir maps a per-phase state directory to its phase label,
// used as the middle segment of the S3 key. Defaults to "bnk" (the
// trial/`state/` dir).
func phaseFromStateDir(stateDir string) string {
	switch filepath.Base(stateDir) {
	case "state-cluster":
		return "cluster"
	case "state-testing":
		return "testing"
	case "state-gateway":
		return "gateway"
	case "state-flp":
		return "flp"
	case "state-tgw":
		return "tgw"
	default:
		return "bnk"
	}
}

// requireTerraformVersion fails if the terraform at tfBin is older than
// major.minor. The s3 backend's native lockfile (`use_lockfile`) — the
// only COS-compatible lock (no DynamoDB) — needs terraform >= 1.10, so we
// fail fast with an actionable message rather than mid-apply.
func requireTerraformVersion(ctx context.Context, tfBin string, major, minor int) error {
	out, err := exec.CommandContext(ctx, tfBin, "version", "-json").Output()
	if err != nil {
		return fmt.Errorf("checking terraform version (needed for state.backend = s3): %w", err)
	}
	var v struct {
		TerraformVersion string `json:"terraform_version"`
	}
	if err := json.Unmarshal(out, &v); err != nil {
		return fmt.Errorf("parsing terraform version: %w", err)
	}
	if !tfVersionAtLeast(v.TerraformVersion, major, minor) {
		return fmt.Errorf("state.backend = \"s3\" needs terraform >= %d.%d (the native S3 lockfile); found %s — upgrade terraform or use the all-in-one runner image",
			major, minor, v.TerraformVersion)
	}
	return nil
}

// tfVersionAtLeast reports whether the dotted version `have` (e.g.
// "1.10.5") is >= major.minor. Compares only major/minor — patch is
// irrelevant for a feature-availability floor.
func tfVersionAtLeast(have string, major, minor int) bool {
	var ma, mi int
	// Sscanf stops at the first non-matching rune, so "1.10.5" → ma=1, mi=10.
	if _, err := fmt.Sscanf(have, "%d.%d", &ma, &mi); err != nil {
		return false
	}
	return ma > major || (ma == major && mi >= minor)
}

// resolveCOSHMAC reads the COS HMAC access/secret keys from the env vars
// named by the config (env-first). When a source is unset it defaults to
// ROKSBNKCTL_COS_HMAC_{ACCESS,SECRET}_KEY, falling back to the standard
// AWS_{ACCESS_KEY_ID,SECRET_ACCESS_KEY}. The keys are returned for env
// injection; never logged or written to disk.
func resolveCOSHMAC(s3 *config.StateS3Cfg) (access, secret string, err error) {
	accVar := s3.AccessKeySource
	if accVar == "" {
		accVar = "ROKSBNKCTL_COS_HMAC_ACCESS_KEY"
	}
	secVar := s3.SecretKeySource
	if secVar == "" {
		secVar = "ROKSBNKCTL_COS_HMAC_SECRET_KEY"
	}
	access = os.Getenv(accVar)
	if access == "" && s3.AccessKeySource == "" {
		access = os.Getenv("AWS_ACCESS_KEY_ID")
	}
	secret = os.Getenv(secVar)
	if secret == "" && s3.SecretKeySource == "" {
		secret = os.Getenv("AWS_SECRET_ACCESS_KEY")
	}
	if access == "" || secret == "" {
		return "", "", fmt.Errorf("state.backend = \"s3\": COS HMAC keys not found — set %s and %s (or AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY)", accVar, secVar)
	}
	return access, secret, nil
}
