package tf

import (
	"fmt"
	"io"
	"os"

	"github.com/jgruberf5/roksctl/internal/config"
)

// WriteTFVars renders the workspace config into terraform.tfvars at path.
// Excludes the API key, which is passed via TF_VAR_ibmcloud_api_key env
// var when terraform is invoked.
//
// kubeconfigDir / scratchDir are rendered when non-empty. Both require
// the upstream TF to declare matching root-level variables (kubeconfig_dir
// in v0.6.8+, scratch_dir in v0.6.9+); older versions warn but tolerate
// the undeclared values.
func WriteTFVars(path string, ws *config.Workspace, kubeconfigDir, scratchDir string) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating %s: %w", path, err)
	}
	defer f.Close()
	return RenderTFVars(f, ws, kubeconfigDir, scratchDir)
}

// RenderTFVars writes the tfvars body to w. Exposed for tests / callers
// that want to inspect the rendering before committing it to disk.
//
// Only fields the user has explicitly set in config.yaml are emitted —
// the rest fall through to the upstream TF module's own defaults.
//
// kubeconfigDir + scratchDir are roksctl-managed paths threaded into the
// upstream TF; the upstream defaults for both target the bnk runner
// image's /work mount, which doesn't exist on a host filesystem.
//
// IMPORTANT: api_key is NEVER written. Pass it via the
// TF_VAR_ibmcloud_api_key env var on the terraform invocation.
func RenderTFVars(w io.Writer, ws *config.Workspace, kubeconfigDir, scratchDir string) error {
	if _, err := fmt.Fprintln(w, "# Generated by roksctl. Do not edit by hand — run `roksctl init` to update."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "# IBMCLOUD_API_KEY is NOT written here; it's passed via TF_VAR env var."); err != nil {
		return err
	}
	fmt.Fprintln(w)

	// IBM Cloud
	if ws.IBMCloud.Region != "" {
		fmt.Fprintf(w, "ibmcloud_cluster_region = %q\n", ws.IBMCloud.Region)
	}
	if ws.IBMCloud.ResourceGroup != "" {
		fmt.Fprintf(w, "ibmcloud_resource_group = %q\n", ws.IBMCloud.ResourceGroup)
	}

	// Cluster — branching on Create chooses which TF variable name carries
	// the cluster identity. The upstream module uses different names for
	// new (openshift_cluster_name) vs existing (roks_cluster_id_or_name).
	fmt.Fprintf(w, "create_roks_cluster = %v\n", ws.Cluster.Create)
	if ws.Cluster.Create {
		if ws.Cluster.Name != "" {
			fmt.Fprintf(w, "openshift_cluster_name = %q\n", ws.Cluster.Name)
		}
		if ws.Cluster.OpenShiftVersion != "" {
			fmt.Fprintf(w, "openshift_cluster_version = %q\n", ws.Cluster.OpenShiftVersion)
		}
		if ws.Cluster.WorkersPerZone > 0 {
			fmt.Fprintf(w, "roks_workers_per_zone = %d\n", ws.Cluster.WorkersPerZone)
		}
	} else {
		if ws.Cluster.Name != "" {
			fmt.Fprintf(w, "roks_cluster_id_or_name = %q\n", ws.Cluster.Name)
		}
	}

	// BNK
	if ws.BNK.CNEInstanceSize != "" {
		fmt.Fprintf(w, "cneinstance_deployment_size = %q\n", ws.BNK.CNEInstanceSize)
	}
	if ws.BNK.FARRepoURL != "" {
		fmt.Fprintf(w, "far_repo_url = %q\n", ws.BNK.FARRepoURL)
	}
	if ws.BNK.ManifestVersion != "" {
		fmt.Fprintf(w, "f5_bigip_k8s_manifest_version = %q\n", ws.BNK.ManifestVersion)
	}

	// Kubeconfig scratch dir. Overrides the module-internal /work/.bnk/...
	// default which only works inside the bnk runner image. Threaded to
	// each submodule by the root TF (v0.6.8+); older TF versions print a
	// "variable not declared" warning but otherwise behave the same.
	if kubeconfigDir != "" {
		fmt.Fprintf(w, "kubeconfig_dir = %q\n", kubeconfigDir)
	}

	// FLO scratch dir for FAR auth tarball + f5-manifest extraction.
	// Same /work problem class as kubeconfig_dir. Threaded by the root
	// TF (v0.6.9+) to module.flo, which derives manifest_download_dir
	// as ${scratch_dir}/f5-manifest automatically.
	if scratchDir != "" {
		fmt.Fprintf(w, "scratch_dir = %q\n", scratchDir)
	}

	return nil
}
