package tf

import (
	"fmt"
	"io"
	"os"

	"github.com/jgruberf5/roksbnkctl/internal/config"
	"github.com/jgruberf5/roksbnkctl/internal/naming"
)

// WriteTFVars renders the workspace config into terraform.tfvars at path.
// Excludes the API key, which is passed via TF_VAR_ibmcloud_api_key env
// var when terraform is invoked.
//
// kubeconfigDir / scratchDir are rendered when non-empty. Both require
// the upstream TF to declare matching root-level variables (kubeconfig_dir
// in v0.6.8+, scratch_dir in v0.6.9+); older versions warn but tolerate
// the undeclared values.
func WriteTFVars(path string, ws *config.Workspace, kubeconfigDir, scratchDir string) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating %s: %w", path, err)
	}
	defer f.Close()
	return RenderTFVars(f, ws, kubeconfigDir, scratchDir)
}

// RenderTFVars writes the tfvars body to w. Exposed for tests / callers
// that want to inspect the rendering before committing it to disk.
//
// Two render modes, selected by ws.Prefix:
//
//   - ws.Prefix == "" (legacy config): the SPARSE render — only the fields
//     the user explicitly set in config.yaml are emitted; every resource
//     name falls through to the upstream TF module defaults. This path is
//     byte-identical to pre-Sprint-26 and is what an un-migrated
//     config.yaml renders.
//   - ws.Prefix != "" (Sprint 26 prefix-driven config): the FULL render —
//     every account-scoped resource NAME is derived from the prefix via
//     internal/naming.Derive and emitted, alongside each resource's
//     create/reuse toggle, so two workspaces that both create infra no
//     longer collide on the upstream module's default names. Each variable
//     is emitted EXACTLY ONCE (in-file duplicates are a terraform error);
//     the separate bnk-phase-override.tfvars (live second-phase handoff)
//     and any terraform.tfvars.user still layer LAST as their own
//     -var-file and override these via terraform's last-wins precedence —
//     they are cross-file, never in-file duplicates.
//
// kubeconfigDir + scratchDir are roksbnkctl-managed paths threaded into the
// upstream TF; the upstream defaults for both target the bnk runner
// image's /work mount, which doesn't exist on a host filesystem.
//
// IMPORTANT: api_key is NEVER written. Pass it via the
// TF_VAR_ibmcloud_api_key env var on the terraform invocation.
func RenderTFVars(w io.Writer, ws *config.Workspace, kubeconfigDir, scratchDir string) error {
	if _, err := fmt.Fprintln(w, "# Generated by roksbnkctl. Do not edit by hand — run `roksbnkctl init` to update."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "# IBMCLOUD_API_KEY is NOT written here; it's passed via TF_VAR env var."); err != nil {
		return err
	}
	fmt.Fprintln(w)

	if ws.Prefix != "" {
		if err := renderFullBody(w, ws); err != nil {
			return err
		}
	} else {
		if err := renderSparseBody(w, ws); err != nil {
			return err
		}
	}

	// Kubeconfig scratch dir. Overrides the module-internal /work/.bnk/...
	// default which only works inside the bnk runner image. Threaded to
	// each submodule by the root TF (v0.6.8+); older TF versions print a
	// "variable not declared" warning but otherwise behave the same.
	if kubeconfigDir != "" {
		fmt.Fprintf(w, "kubeconfig_dir = %q\n", kubeconfigDir)
	}

	// FLO scratch dir for FAR auth tarball + f5-manifest extraction.
	// Same /work problem class as kubeconfig_dir. Threaded by the root
	// TF (v0.6.9+) to module.flo, which derives manifest_download_dir
	// as ${scratch_dir}/f5-manifest automatically.
	if scratchDir != "" {
		fmt.Fprintf(w, "scratch_dir = %q\n", scratchDir)
	}

	return nil
}

// renderSparseBody is the legacy (empty-Prefix) render body: only fields the
// user explicitly set in config.yaml are emitted; resource names fall
// through to the upstream module defaults. Byte-identical to pre-Sprint-26.
func renderSparseBody(w io.Writer, ws *config.Workspace) error {
	// IBM Cloud
	if ws.IBMCloud.Region != "" {
		fmt.Fprintf(w, "ibmcloud_cluster_region = %q\n", ws.IBMCloud.Region)
	}
	if ws.IBMCloud.ResourceGroup != "" {
		fmt.Fprintf(w, "ibmcloud_resource_group = %q\n", ws.IBMCloud.ResourceGroup)
	}

	// Cluster — branching on Create chooses which TF variable name carries
	// the cluster identity. The upstream module uses different names for
	// new (openshift_cluster_name) vs existing (roks_cluster_id_or_name).
	fmt.Fprintf(w, "create_roks_cluster = %v\n", ws.Cluster.Create)
	if ws.Cluster.Create {
		if ws.Cluster.Name != "" {
			fmt.Fprintf(w, "openshift_cluster_name = %q\n", ws.Cluster.Name)
		}
		if ws.Cluster.OpenShiftVersion != "" {
			fmt.Fprintf(w, "openshift_cluster_version = %q\n", ws.Cluster.OpenShiftVersion)
		}
		if ws.Cluster.WorkersPerZone > 0 {
			fmt.Fprintf(w, "roks_workers_per_zone = %d\n", ws.Cluster.WorkersPerZone)
		}
	} else {
		if ws.Cluster.Name != "" {
			fmt.Fprintf(w, "roks_cluster_id_or_name = %q\n", ws.Cluster.Name)
		}
	}

	renderBNKFields(w, ws)
	return nil
}

// renderFullBody is the Sprint 26 prefix-driven render body: it derives the
// full account-scoped name set from ws.Prefix and emits each resource's
// create/reuse toggle + name EXACTLY ONCE. The operator's first-phase
// intent is captured here; the separate phase-override + user var-files
// layer last and override via terraform precedence (cross-file, not
// in-file).
//
// A resource's name carrier depends on its create toggle: a CREATED
// resource gets the prefix-derived name (so two workspaces don't collide);
// a DECLINED-but-depended-on resource gets the operator's Existing name/ID
// so the dependent looks it up by name.
func renderFullBody(w io.Writer, ws *config.Workspace) error {
	plan := naming.Derive(ws.Prefix)

	// Resources may be nil on a prefix-set config that predates the
	// resources block (defensive); treat a nil block as all-create with no
	// existing refs, matching the --var-file default.
	res := ws.Resources
	if res == nil {
		res = &config.ResourcesCfg{
			TransitGateway:   config.ResourceToggle{Create: true},
			RegistryCOS:      config.ResourceToggle{Create: true},
			CertManager:      config.ResourceToggle{Create: true},
			BNK:              config.ResourceToggle{Create: true},
			TGWJumphost:      config.ResourceToggle{Create: true},
			ClusterJumphosts: config.ResourceToggle{Create: true},
			ClientVPC:        config.ResourceToggle{Create: true},
		}
	}

	// IBM Cloud region + resource group.
	if ws.IBMCloud.Region != "" {
		fmt.Fprintf(w, "ibmcloud_cluster_region = %q\n", ws.IBMCloud.Region)
	}
	if ws.IBMCloud.ResourceGroup != "" {
		fmt.Fprintf(w, "ibmcloud_resource_group = %q\n", ws.IBMCloud.ResourceGroup)
	}

	// Cluster. Created → openshift_cluster_name = <prefix>; existing →
	// roks_cluster_id_or_name = <Cluster.Name>. Reuses ClusterCfg, where
	// Name doubles as the existing id/name when Create=false.
	fmt.Fprintf(w, "create_roks_cluster = %v\n", ws.Cluster.Create)
	if ws.Cluster.Create {
		fmt.Fprintf(w, "openshift_cluster_name = %q\n", plan.ClusterName)
		if ws.Cluster.OpenShiftVersion != "" {
			fmt.Fprintf(w, "openshift_cluster_version = %q\n", ws.Cluster.OpenShiftVersion)
		}
		if ws.Cluster.WorkersPerZone > 0 {
			fmt.Fprintf(w, "roks_workers_per_zone = %d\n", ws.Cluster.WorkersPerZone)
		}
	} else if ws.Cluster.Name != "" {
		fmt.Fprintf(w, "roks_cluster_id_or_name = %q\n", ws.Cluster.Name)
	}

	// Cluster VPC — always created by the cluster phase under the derived
	// name (no standalone toggle; it follows the cluster).
	fmt.Fprintf(w, "roks_cluster_vpc_name = %q\n", plan.ClusterVPCName)

	// Registry COS instance. Only meaningful when the cluster is created;
	// the upstream count gate is (create_cluster && create_cos_instance).
	fmt.Fprintf(w, "create_roks_registry_cos_instance = %v\n", res.RegistryCOS.Create)
	if res.RegistryCOS.Create {
		fmt.Fprintf(w, "roks_cos_instance_name = %q\n", plan.COSInstanceName)
	} else if res.RegistryCOS.Existing != "" {
		fmt.Fprintf(w, "roks_cos_instance_name = %q\n", res.RegistryCOS.Existing)
	}

	// Transit gateway.
	fmt.Fprintf(w, "create_roks_transit_gateway = %v\n", res.TransitGateway.Create)
	if res.TransitGateway.Create {
		fmt.Fprintf(w, "roks_transit_gateway_name = %q\n", plan.TransitGatewayName)
	} else if res.TransitGateway.Existing != "" {
		fmt.Fprintf(w, "roks_transit_gateway_name = %q\n", res.TransitGateway.Existing)
	}

	// In-cluster services (no prefixed names; namespaces stay fixed).
	fmt.Fprintf(w, "install_cert_manager = %v\n", res.CertManager.Create)
	fmt.Fprintf(w, "deploy_bnk = %v\n", res.BNK.Create)

	// TGW test jumphost.
	fmt.Fprintf(w, "testing_create_tgw_jumphost = %v\n", res.TGWJumphost.Create)
	if res.TGWJumphost.Create {
		fmt.Fprintf(w, "testing_tgw_jumphost_name = %q\n", plan.TGWJumphostName)
	}

	// Client VPC (for the TGW jumphost).
	fmt.Fprintf(w, "testing_create_client_vpc = %v\n", res.ClientVPC.Create)
	if res.ClientVPC.Create {
		fmt.Fprintf(w, "testing_client_vpc_name = %q\n", plan.ClientVPCName)
	} else if res.ClientVPC.Existing != "" {
		fmt.Fprintf(w, "testing_client_vpc_name = %q\n", res.ClientVPC.Existing)
	}

	// Per-zone cluster jumphosts (the module appends -<zone> to the prefix).
	fmt.Fprintf(w, "testing_create_cluster_jumphosts = %v\n", res.ClusterJumphosts.Create)
	if res.ClusterJumphosts.Create {
		fmt.Fprintf(w, "testing_cluster_jumphost_name_prefix = %q\n", plan.ClusterJumphostPrefix)
	}

	renderBNKFields(w, ws)
	renderGatewayFields(w, ws)
	return nil
}

// renderGatewayFields emits gateway_* overrides for the Gateway phase. Each is
// emitted only when config.yaml sets it; unset → the terraform gateway module's
// install-guide defaults apply. Harmless in the other phases' tfvars (their
// override forces deploy_gateway=false, so the gateway module is count=0).
func renderGatewayFields(w io.Writer, ws *config.Workspace) {
	g := ws.Gateway
	if g.AppNamespace != "" {
		fmt.Fprintf(w, "gateway_app_namespace = %q\n", g.AppNamespace)
	}
	if g.BackendService != "" {
		fmt.Fprintf(w, "gateway_backend_service = %q\n", g.BackendService)
	}
	if g.BackendPort != 0 {
		fmt.Fprintf(w, "gateway_backend_port = %d\n", g.BackendPort)
	}
	if g.EgressMode != "" {
		fmt.Fprintf(w, "gateway_egress_mode = %q\n", g.EgressMode)
	}
	if g.ClientSubnetLocal != "" {
		fmt.Fprintf(w, "gateway_client_subnet_local = %q\n", g.ClientSubnetLocal)
	}
	if g.ClientSubnetRemote != "" {
		fmt.Fprintf(w, "gateway_client_subnet_remote = %q\n", g.ClientSubnetRemote)
	}
	if g.VXLANPort != 0 {
		fmt.Fprintf(w, "gateway_vxlan_port = %d\n", g.VXLANPort)
	}
}

// renderBNKFields emits the BNK tuning fields shared by both render modes.
// Each is emitted only when set in config.yaml, so neither render path
// duplicates a variable.
func renderBNKFields(w io.Writer, ws *config.Workspace) {
	if ws.BNK.CNEInstanceSize != "" {
		fmt.Fprintf(w, "cneinstance_deployment_size = %q\n", ws.BNK.CNEInstanceSize)
	}
	if ws.BNK.FARRepoURL != "" {
		fmt.Fprintf(w, "far_repo_url = %q\n", ws.BNK.FARRepoURL)
	}
	if ws.BNK.ManifestVersion != "" {
		fmt.Fprintf(w, "f5_bigip_k8s_manifest_version = %q\n", ws.BNK.ManifestVersion)
	}
	// Sprint 27 install-mode flag. Emitted only when set; an unset value
	// lets the upstream TF default (kubectl) stand, keeping older configs
	// byte-identical. "legacy_curl" selects the null_resource baseline.
	if ws.BNK.CRMode != "" {
		fmt.Fprintf(w, "bnk_cr_mode = %q\n", ws.BNK.CRMode)
	}
	// Cloud-network-mapping + VLAN zones (BNK install-guide "Configuration").
	// Emitted only when config.yaml supplies them; absent → the terraform
	// module's install-guide defaults apply (existing configs unchanged).
	if ws.BNK.Network != nil && len(ws.BNK.Network.Zones) > 0 {
		renderNetworkZones(w, ws.BNK.Network.Zones)
	}
}

// renderNetworkZones emits the cneinstance_network_zones HCL list-of-objects
// from the bnk.network.zones config block. Field names match the terraform
// object type exactly so the render is a drop-in override.
func renderNetworkZones(w io.Writer, zones []config.BNKZoneCfg) {
	fmt.Fprintln(w, "cneinstance_network_zones = [")
	for _, z := range zones {
		fmt.Fprintln(w, "  {")
		fmt.Fprintf(w, "    ext_vlan_cidr   = %q\n", z.ExtVLANCIDR)
		fmt.Fprintf(w, "    int_vlan_cidr   = %q\n", z.IntVLANCIDR)
		fmt.Fprintf(w, "    int_snat_cidr   = %q\n", z.IntSNATCIDR)
		fmt.Fprintf(w, "    int_vip_cidr    = %q\n", z.IntVIPCIDR)
		fmt.Fprintf(w, "    external_selfip = %q\n", z.ExternalSelfIP)
		fmt.Fprintf(w, "    internal_selfip = %q\n", z.InternalSelfIP)
		fmt.Fprintln(w, "  },")
	}
	fmt.Fprintln(w, "]")
}
