apiVersion: v1
clusters:
- cluster:
    server: https://c115-e.us-south.containers.cloud.ibm.com:30571
  name: tf-roks-cluster-t1-2014/d7sftiod0ftt2lo6tt90
- cluster:
    server: https://c115-e.us-south.containers.cloud.ibm.com:30571
  name: c115-e-us-south-containers-cloud-ibm-com:30571
contexts:
- context:
    cluster: tf-roks-cluster-t1-2014/d7sftiod0ftt2lo6tt90
    namespace: default
    user: ""
  name: tf-roks-cluster-t1-2014/d7sftiod0ftt2lo6tt90
- context:
    cluster: c115-e-us-south-containers-cloud-ibm-com:30571
    namespace: default
    user: IAM#j.gruber@f5.com/c115-e-us-south-containers-cloud-ibm-com:30571
  name: default/c115-e-us-south-containers-cloud-ibm-com:30571/IAM#j.gruber@f5.com
current-context: default/c115-e-us-south-containers-cloud-ibm-com:30571/IAM#j.gruber@f5.com
kind: Config
users:
- name: IAM#j.gruber@f5.com/c115-e-us-south-containers-cloud-ibm-com:30571
  user:
    token: sha256~cqDIZqMXCTkzXw6PfBP5gu6kWVLxuZtxWv3NrQAoniA
