// Command cobra-md walks the roksbnkctl cobra command tree and emits a
// single Markdown reference document on stdout.
//
// Usage:
//
//	go run ./tools/refgen/cobra-md > book/src/27-command-reference.md
//
// Re-run on every CLI surface change. The output is checked into the
// book/ directory; the generator itself isn't part of the release
// binary.
//
// Why a custom generator instead of `cobra-cli docs` / spf13/cobra/doc?
//
//   - We want a SINGLE markdown file (chapter 27), not per-command
//     files spf13/cobra/doc emits.
//   - We need control over heading depth + flag-table shape to match
//     the rest of the book.
//   - Inherited (persistent) flags are rendered ONCE at the top of the
//     chapter rather than repeated per subcommand — keeps the chapter
//     scannable.
//
// PLAN.md Sprint 6 row §"Code/config deliverables" calls out the
// chapter-27 generator explicitly; this is its implementation.
package main

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/jgruberf5/roksbnkctl/internal/cli"
)

func main() {
	root := cli.RootCommand()
	if err := render(os.Stdout, root); err != nil {
		fmt.Fprintf(os.Stderr, "cobra-md: %v\n", err)
		os.Exit(1)
	}
}

// render writes the full reference document to w.
//
// Layout:
//
//	# Command reference
//	  (auto-generation note)
//	## Global flags
//	  (PersistentFlags from the root; rendered once)
//	## roksbnkctl <verb>
//	  short + long description, local-flags table, examples, parent backlink
//	### roksbnkctl <verb> <subverb>
//	  ...
//	#### roksbnkctl <verb> <subverb> <sub-sub>
//	  ...
//
// Hidden commands (Hidden=true) and the help command are skipped; they
// don't carry user-facing semantics.
func render(w io.Writer, root *cobra.Command) error {
	if root == nil {
		return fmt.Errorf("nil root command")
	}

	fmt.Fprintln(w, "# Command reference")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Auto-generated by `go run ./tools/refgen/cobra-md > book/src/27-command-reference.md`. Re-run on every CLI surface change.")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "%s\n\n", strings.TrimSpace(root.Long))
	fmt.Fprintln(w)

	// Global flags (persistent on the root) — rendered once at the top
	// so per-command sections don't repeat them.
	if root.PersistentFlags().HasFlags() {
		fmt.Fprintln(w, "## Global flags")
		fmt.Fprintln(w)
		fmt.Fprintln(w, "These flags apply to every command. They are declared on the root command and inherited by every subcommand.")
		fmt.Fprintln(w)
		writeFlagTable(w, root.PersistentFlags())
		fmt.Fprintln(w)
	}

	// Top-level commands, alphabetised for stable diffs.
	children := visibleSubcommands(root)
	sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })

	for _, c := range children {
		renderCommand(w, c, 2)
	}
	return nil
}

// renderCommand emits one section for c at the given heading depth
// (2 = `##`, 3 = `###`, …). Recurses into visible subcommands. Caps
// depth at 6 (Markdown's max heading level); deeper subcommand trees
// would still render but with the heading clamped at H6.
func renderCommand(w io.Writer, c *cobra.Command, depth int) {
	if depth < 2 {
		depth = 2
	}
	if depth > 6 {
		depth = 6
	}
	hash := strings.Repeat("#", depth)
	path := c.CommandPath()

	fmt.Fprintf(w, "%s `%s`\n\n", hash, path)

	if s := strings.TrimSpace(c.Short); s != "" {
		fmt.Fprintf(w, "%s\n\n", s)
	}

	// Aliases — emitted under the synopsis so readers searching for the
	// short form (e.g. `ws` for `workspaces`) find the section. The rest
	// of the book uses the alias forms universally; chapter 27 follows
	// cobra's canonical `Use` value for the heading + path.
	if len(c.Aliases) > 0 {
		quoted := make([]string, 0, len(c.Aliases))
		for _, a := range c.Aliases {
			quoted = append(quoted, fmt.Sprintf("`%s`", a))
		}
		fmt.Fprintf(w, "**Aliases**: %s\n\n", strings.Join(quoted, ", "))
	}

	// Synopsis: cobra's UseLine() returns the FULL command path plus
	// the Use suffix (`roksbnkctl ws delete [flags] <name>`). Render it
	// verbatim inside a fenced block when it adds info beyond the path
	// alone (i.e. when there's a "[flags]" / "<arg>" suffix).
	useLine := strings.TrimSpace(c.UseLine())
	if useLine != "" && useLine != path {
		fmt.Fprintf(w, "```\n%s\n```\n\n", useLine)
	}

	// Long description, if present and distinct from Short.
	if l := strings.TrimSpace(c.Long); l != "" && l != strings.TrimSpace(c.Short) {
		fmt.Fprintf(w, "%s\n\n", l)
	}

	// Local flag table (NOT inherited — those live in `## Global flags`).
	if c.HasLocalFlags() && c.LocalFlags().HasFlags() {
		fmt.Fprintln(w, "**Flags**")
		fmt.Fprintln(w)
		writeFlagTable(w, c.LocalFlags())
		fmt.Fprintln(w)
	}

	// Examples block — cobra's Example is a free-form string; render
	// verbatim inside a shell code fence.
	if e := strings.TrimSpace(c.Example); e != "" {
		fmt.Fprintln(w, "**Examples**")
		fmt.Fprintln(w)
		fmt.Fprintln(w, "```bash")
		fmt.Fprintln(w, e)
		fmt.Fprintln(w, "```")
		fmt.Fprintln(w)
	}

	// Parent backlink — except at depth 2 (top-level command; parent is
	// "roksbnkctl" itself which is the chapter title, not a section).
	if depth > 2 && c.Parent() != nil {
		parent := c.Parent().CommandPath()
		anchor := slugify(parent)
		fmt.Fprintf(w, "← back to [`%s`](#%s)\n\n", parent, anchor)
	}

	// Recurse into visible subcommands at depth+1.
	subs := visibleSubcommands(c)
	sort.Slice(subs, func(i, j int) bool { return subs[i].Name() < subs[j].Name() })
	for _, sc := range subs {
		renderCommand(w, sc, depth+1)
	}
}

// visibleSubcommands returns c's user-facing subcommands. Hidden
// commands and the auto-generated "help" pseudo-command are skipped.
func visibleSubcommands(c *cobra.Command) []*cobra.Command {
	if c == nil {
		return nil
	}
	out := make([]*cobra.Command, 0, len(c.Commands()))
	for _, sub := range c.Commands() {
		if sub.Hidden {
			continue
		}
		if sub.Name() == "help" {
			continue
		}
		out = append(out, sub)
	}
	return out
}

// writeFlagTable emits a Markdown table for the given flag set. Hidden
// flags are skipped. Each row: `| --flag | default | description |`.
// The table is sorted by long name for stable diffs.
//
// Short flags (e.g. `-v`) are rendered alongside the long form when
// present: `--verbose / -v`. Default values render as a literal code
// span; the empty default is rendered as a dash so the column doesn't
// look ragged.
func writeFlagTable(w io.Writer, fs *pflag.FlagSet) {
	type row struct {
		name        string
		short       string
		typ         string
		def         string
		description string
	}
	var rows []row
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		rows = append(rows, row{
			name:        f.Name,
			short:       f.Shorthand,
			typ:         f.Value.Type(),
			def:         f.DefValue,
			description: strings.ReplaceAll(f.Usage, "|", `\|`),
		})
	})
	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })

	fmt.Fprintln(w, "| Flag | Type | Default | Description |")
	fmt.Fprintln(w, "|---|---|---|---|")
	for _, r := range rows {
		flag := "`--" + r.name + "`"
		if r.short != "" {
			flag = "`--" + r.name + "` / `-" + r.short + "`"
		}
		def := "—"
		if r.def != "" {
			def = "`" + r.def + "`"
		}
		fmt.Fprintf(w, "| %s | `%s` | %s | %s |\n", flag, r.typ, def, r.description)
	}
}

// slugify maps a command path like "roksbnkctl ws delete" to the
// GitHub-Pages anchor "roksbnkctl-ws-delete" that mdBook generates
// for a backtick-wrapped header at any depth. mdBook's anchor
// algorithm: lowercase, replace any non-alphanumeric run with `-`,
// trim leading/trailing dashes, drop backticks.
func slugify(s string) string {
	var b strings.Builder
	prevDash := true
	for _, r := range strings.ToLower(s) {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			b.WriteRune(r)
			prevDash = false
		default:
			if !prevDash {
				b.WriteRune('-')
				prevDash = true
			}
		}
	}
	out := b.String()
	out = strings.TrimRight(out, "-")
	return out
}
