package main

import (
	"bytes"
	"regexp"
	"strings"
	"testing"

	"github.com/jgruberf5/roksbnkctl/internal/cli"
)

// TestRender_SmokeOutput verifies the generator emits a well-formed
// reference chapter for the live root command tree:
//
//   - the chapter starts with the expected H1
//   - the global-flags section is present (the root has persistent
//     flags by design)
//   - at least one known top-level command (init) renders with a
//     fenced synopsis
//   - markdown tables are balanced (every `|`-separated header row has
//     a matching separator row with `---` cells)
//   - code fences are balanced (even number of triple-backticks)
//
// Failing one of these would indicate the generator drifted in a way
// that produces a broken book chapter — the integration step (architect
// commits the generated chapter) would surface garbage otherwise.
func TestRender_SmokeOutput(t *testing.T) {
	var buf bytes.Buffer
	if err := render(&buf, cli.RootCommand()); err != nil {
		t.Fatalf("render: %v", err)
	}
	out := buf.String()

	if !strings.HasPrefix(out, "# Command reference\n") {
		t.Fatalf("output does not start with `# Command reference` header; got:\n%s", firstLines(out, 5))
	}
	if !strings.Contains(out, "Auto-generated by `go run ./tools/refgen/cobra-md") {
		t.Errorf("output missing auto-generation note")
	}
	if !strings.Contains(out, "## Global flags") {
		t.Errorf("output missing `## Global flags` section")
	}
	if !strings.Contains(out, "## `roksbnkctl init`") {
		t.Errorf("output missing top-level `roksbnkctl init` section; got headings:\n%s", grepLines(out, "^#"))
	}
	if !strings.Contains(out, "## `roksbnkctl doctor`") {
		t.Errorf("output missing top-level `roksbnkctl doctor` section; got headings:\n%s", grepLines(out, "^#"))
	}

	// Balanced code fences: count triple-backticks at line starts; must
	// be even (every opener has a closer).
	fences := strings.Count(out, "\n```")
	if out[:3] == "```" {
		fences++ // first-line opener
	}
	if fences%2 != 0 {
		t.Errorf("unbalanced code fences: %d (expected even)", fences)
	}

	// Markdown table sanity: every "| Flag |" header line is followed by
	// a "|---" separator within the next 2 lines.
	lines := strings.Split(out, "\n")
	re := regexp.MustCompile(`^\|.*\|$`)
	for i, ln := range lines {
		if !strings.HasPrefix(ln, "| Flag |") {
			continue
		}
		if i+1 >= len(lines) {
			t.Errorf("flag-table header at line %d has no separator (EOF)", i+1)
			continue
		}
		sep := lines[i+1]
		if !re.MatchString(sep) || !strings.Contains(sep, "---") {
			t.Errorf("flag-table at line %d missing separator row; got %q", i+1, sep)
		}
	}
}

// TestSlugify exercises a few corner cases of the mdBook-anchor
// algorithm: leading/trailing punctuation, multi-word commands, and
// pure-ASCII content. The algorithm is hot-pathed in renderCommand's
// backlink emission; a regression would break every parent link in the
// chapter.
func TestSlugify(t *testing.T) {
	tests := []struct {
		in, want string
	}{
		{"roksbnkctl", "roksbnkctl"},
		{"roksbnkctl ws", "roksbnkctl-ws"},
		{"roksbnkctl ws delete", "roksbnkctl-ws-delete"},
		{"roksbnkctl  multi  space", "roksbnkctl-multi-space"},
	}
	for _, tc := range tests {
		if got := slugify(tc.in); got != tc.want {
			t.Errorf("slugify(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func firstLines(s string, n int) string {
	parts := strings.SplitN(s, "\n", n+1)
	if len(parts) > n {
		parts = parts[:n]
	}
	return strings.Join(parts, "\n")
}

func grepLines(s, pattern string) string {
	re := regexp.MustCompile(pattern)
	var b strings.Builder
	for _, ln := range strings.Split(s, "\n") {
		if re.MatchString(ln) {
			b.WriteString(ln)
			b.WriteByte('\n')
		}
	}
	return b.String()
}
