apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: scn-proxyproto-gateway
  namespace: {{.Namespace}}
spec:
  gatewayClassName: {{.GatewayClassName}}
  addresses:
  - type: IPAddress
    value: {{.VIP}}
  listeners:
  - name: tcp-listener
    protocol: TCP
    port: 80
    allowedRoutes:
      namespaces: {from: Same}
