apiVersion: gateway.k8s.f5net.com/v1
kind: L4Route
metadata:
  name: scn-proxyproto-route
  namespace: {{.Namespace}}
spec:
  parentRefs:
  - name: scn-proxyproto-gateway
    sectionName: tcp-listener
  protocol: TCP
  pvaAccelerationMode: disabled
  rules:
  - backendRefs:
    - name: proxy-backend
      port: 80
