package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// #219. A user's `bnk down` died on
//
//	Error: Missing item separator
//	  on .../.applied-replay.tfvars line 6:
//	   5: cneinstance_network_zones = [
//	   6: cneinstance_tmm_k8s_routes = "172.17..."
//
// because the applied snapshot on disk held a truncated block. The snapshot is
// only rewritten on apply, so every retry regenerated the same unparseable file
// and the workspace could not be destroyed at all.

// The reporter's snapshot, reduced. Written by a build that predates multi-line
// value support.
const truncatedSnapshot = `# Generated by roksbnkctl
# === from config.yaml ===
cneinstance_cluster_name = "bnk-test1"
cneinstance_network_zones = [
cneinstance_tmm_k8s_routes = "172.17.0.0/18,172.21.0.0/16,192.168.100.0/24"
prefix = "bnk-test1"
`

func writeTemp(t *testing.T, body string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "terraform.applied.tfvars")
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

// The fragment must not survive into the map. `[` is not a value; re-emitting it
// is what terraform refused to parse.
func TestAnUnterminatedBlockIsDroppedRatherThanKeptAsAFragment(t *testing.T) {
	got, _, err := readTFVarsAssignments(writeTemp(t, truncatedSnapshot))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if v, ok := got["cneinstance_network_zones"]; ok {
		t.Errorf("kept cneinstance_network_zones = %q.\n"+
			"An unterminated block has no usable value; writing it back into the replay "+
			"var-file is what made `bnk down` fail with Missing item separator (#219).", v)
	}
}

// The silent half of the defect: the continuation scan ate the rest of the file
// looking for a closing bracket, so a snapshot of four variables parsed to two.
// Nobody reported this one because it produces a wrong answer quietly.
func TestAssignmentsAfterAnUnterminatedBlockSurvive(t *testing.T) {
	got, _, err := readTFVarsAssignments(writeTemp(t, truncatedSnapshot))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	for _, want := range []string{"cneinstance_tmm_k8s_routes", "prefix", "cneinstance_cluster_name"} {
		if _, ok := got[want]; !ok {
			t.Errorf("%q was swallowed by the unterminated block above it.\n"+
				"The replay would silently under-record what the apply actually used. got: %v", want, keysOf(got))
		}
	}
}

// The fix must not cost the feature it is guarding. Well-formed multi-line
// values are the normal case: multizone is the only shape this tool deploys.
func TestWellFormedMultiLineValuesStillRoundTrip(t *testing.T) {
	src := `prefix = "x"
cneinstance_network_zones = [
  {
    ext_vlan_cidr   = "10.243.1.0/24"
    internal_selfip = "10.243.2.10"
  },
  {
    ext_vlan_cidr   = "10.243.3.0/24"
    internal_selfip = "10.243.4.10"
  },
]
cneinstance_tmm_k8s_routes = "172.17.0.0/18"
`
	got, _, err := readTFVarsAssignments(writeTemp(t, src))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	v, ok := got["cneinstance_network_zones"]
	if !ok {
		t.Fatal("a well-formed zone list was dropped — the guard is too eager")
	}
	if !strings.Contains(v, "10.243.3.0/24") {
		t.Errorf("the second zone is missing: %q", v)
	}
	if !strings.HasSuffix(v, "]") {
		t.Errorf("the block did not round-trip closed: %q", v)
	}
	if got["cneinstance_tmm_k8s_routes"] == "" || got["prefix"] == "" {
		t.Errorf("assignments around the block were lost: %v", keysOf(got))
	}
}

// A comment inside a multi-line value must not stop the bracket count. This is
// the regression the exported balance check would otherwise introduce: the
// counter returned at the first `#`, so a commented list read as unbalanced and
// a perfectly good value would be skipped.
func TestACommentInsideABlockDoesNotBreakTheBracketCount(t *testing.T) {
	v := "[\n  # the first zone\n  {\n    a = \"b\"  # trailing\n  },\n]"
	if HCLValueIsUnbalanced(v) {
		t.Errorf("a balanced list containing comments was reported unbalanced:\n%s", v)
	}
	if !HCLValueIsUnbalanced("[\n  {\n") {
		t.Error("a genuinely unbalanced value was reported balanced")
	}
	if HCLValueIsUnbalanced(`"a string with a # and a ] in it"`) {
		t.Error("brackets inside a quoted string were counted")
	}
}

// The guard has to survive a snapshot that is malformed in the other direction
// too, rather than trading one unparseable file for a panic.
func TestAStrayClosingBracketDoesNotBreakParsing(t *testing.T) {
	got, _, err := readTFVarsAssignments(writeTemp(t, "prefix = \"x\"\nbad = ]\nafter = \"kept\"\n"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if got["after"] != `"kept"` {
		t.Errorf("assignments after a stray bracket were lost: %v", keysOf(got))
	}
}

func keysOf(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

// ── review fixes ─────────────────────────────────────────────────────────────

// An over-closed block is malformed, not finished. It used to be reported as
// CLOSED while its value was still unbalanced, so the one thing the caller
// relies on that return for was wrong.
func TestAnOverClosedBlockIsNotReportedAsClosed(t *testing.T) {
	got, _, err := readTFVarsAssignments(writeTemp(t, "over = [\n]]\nafter = \"kept\"\n"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if v, ok := got["over"]; ok {
		t.Errorf("recorded over = %q. It closes harder than it opens, so it is malformed "+
			"input and takes the same path as a truncated block: dropped.", v)
	}
	if got["after"] != `"kept"` {
		t.Errorf("assignments after an over-closed block were lost: %v", keysOf(got))
	}
}

// Whatever the parser does record must be emittable. This is the invariant the
// two writers' guards are the backstop for; if it holds, they never fire.
func TestEveryRecordedValueIsBalanced(t *testing.T) {
	src := `good = "scalar"
zones = [
  {
    a = "b"  # trailing comment
  },
]
truncated = [
over = [
]]
tail = "kept"
`
	got, _, err := readTFVarsAssignments(writeTemp(t, src))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	for k, v := range got {
		if HCLValueIsUnbalanced(v) {
			t.Errorf("recorded %s = %q, which no writer can emit", k, v)
		}
	}
	if got["tail"] != `"kept"` {
		t.Errorf("the assignment after two malformed blocks was lost: %v", keysOf(got))
	}
}

// The snapshot writer is the file everything else is derived FROM. Guarding only
// the replay leaves the self-perpetuating half of #219 open.
func TestTheSnapshotWriterAlsoRefusesUnbalancedValues(t *testing.T) {
	dir := t.TempDir()
	src := filepath.Join(dir, "src.tfvars")
	// Reaches the writer's map without going through the block path at all: a
	// bare stray closer is a single-line value as far as the parser is concerned.
	if err := os.WriteFile(src, []byte("stray = ]\nfine = \"yes\"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	out, err := renderAppliedTFVars("trial", []string{src}, time.Now(), "test")
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	for _, line := range strings.Split(out, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") || trimmed == "" {
			continue
		}
		if HCLValueIsUnbalanced(strings.TrimPrefix(trimmed, "stray = ")) && strings.HasPrefix(trimmed, "stray") {
			t.Errorf("the snapshot recorded an unbalanced value:\n  %s\nA corrupt snapshot is "+
				"self-perpetuating, which is the whole mechanism behind #219.", trimmed)
		}
	}
	if !strings.Contains(out, `fine = "yes"`) {
		t.Errorf("a balanced value was dropped from the snapshot:\n%s", out)
	}
	if !strings.Contains(out, "# stray =") {
		t.Errorf("the skipped key was not named in the snapshot:\n%s", out)
	}
}
