apiVersion: v1
clusters:
- cluster:
    server: https://c115-e.us-south.containers.cloud.ibm.com:32381
  name: tf-roks-cluster/d7sm0u1d0ac2dd87uuc0
- cluster:
    server: https://c115-e.us-south.containers.cloud.ibm.com:32381
  name: c115-e-us-south-containers-cloud-ibm-com:32381
contexts:
- context:
    cluster: tf-roks-cluster/d7sm0u1d0ac2dd87uuc0
    namespace: default
    user: ""
  name: tf-roks-cluster/d7sm0u1d0ac2dd87uuc0
- context:
    cluster: c115-e-us-south-containers-cloud-ibm-com:32381
    namespace: default
    user: IAM#j.gruber@f5.com/c115-e-us-south-containers-cloud-ibm-com:32381
  name: default/c115-e-us-south-containers-cloud-ibm-com:32381/IAM#j.gruber@f5.com
current-context: default/c115-e-us-south-containers-cloud-ibm-com:32381/IAM#j.gruber@f5.com
kind: Config
users:
- name: IAM#j.gruber@f5.com/c115-e-us-south-containers-cloud-ibm-com:32381
  user:
    token: sha256~mlYh3EYgrd4Cc5yBA252WgyFVtqB80bFAm6vPNaaJSw
