// Package mdesc prepares free text that is about to be interpolated into
// markdown by the refgen tools.
//
// WHY THIS EXISTS. Chapters 28 and 29 are generated by lifting text the
// generators do not control — Go doc comments off the Workspace struct, and
// `description` strings out of terraform/variables.tf — and dropping it into
// markdown verbatim. Markdown passes raw HTML through by design, so a doc
// comment that says `~/.roksbnkctl/<name>/config.yaml` emits a live <name> tag.
// The browser parses it as an unknown element and renders NOTHING, so the
// published book said "Workspace is ~/.roksbnkctl//config.yaml" — the one word
// on the line telling you it is a placeholder was the word that vanished (#239).
//
// The failure mode is why it survived: an unescaped `|` visibly wrecks a table
// row and got an escaper years ago, while an unescaped `<` silently deletes
// text and looks like prose that was simply written that way.
//
// TWO LAYERS, because they fail differently. Recognised placeholders are wrapped
// in backticks — that is the convention chapter 29 already shipped, and it both
// neutralises the brackets and marks the token as something you substitute.
// Anything angle-bracketed that is NOT a recognised placeholder is HTML-escaped
// instead, so text like "if x <y" cannot open a tag either. Wrapping alone was
// what the previous tfvars-md-local version did, and it is why `<cluster vpc>`
// — a placeholder with a space, outside its identifier pattern — still reached
// the published book as a tag.
//
// CODE SPANS ARE LEFT ALONE. Inside backticks `<name>` is already literal, and
// wrapping it again would emit stray backticks while escaping it would render
// the five characters "&lt;". Both would turn a correct line into a wrong one,
// so Prepare tracks code spans and only acts outside them. That also makes it
// safe to run over text where someone already worked around this by hand —
// terraform/variables.tf has advanced.`<component>`.env[] — and is what makes
// the function idempotent, which matters because the chapters are regenerated
// in place on every build.
package mdesc

import (
	"regexp"
	"strings"
)

// placeholderRE matches a substitutable token: <name>, <flo_namespace>, and —
// the case that reached the published book — <cluster vpc>. The pattern that
// missed that one assumed a placeholder was a single identifier, so allowing a
// second word is the actual fix, but allowing ARBITRARY text between the
// brackets goes too far the other way: "x <y and z> w" would then be read as a
// placeholder rather than two comparisons. Two identifier-ish words is where
// this draws the line.
//
// Getting that line wrong is cosmetic, not a rendering bug. Both branches emit
// markdown that renders the text literally; they differ only in whether it comes
// out code-styled or plain. The failure this package exists to prevent is text
// that renders as NOTHING, and neither branch can produce it.
var placeholderRE = regexp.MustCompile(`^<[a-zA-Z][a-zA-Z0-9_.:/-]*( [a-zA-Z][a-zA-Z0-9_.:/-]*)?>`)

// Prepare makes doc text safe to interpolate into markdown: recognised
// placeholders are backtick-wrapped, any other angle bracket is HTML-escaped,
// and existing code spans are passed through untouched.
func Prepare(s string) string {
	var b strings.Builder
	b.Grow(len(s))

	for i := 0; i < len(s); {
		if s[i] == '`' {
			open := backtickRun(s, i)
			if end := closingRun(s, i+open, open); end >= 0 {
				// A complete code span: copy it through untouched.
				b.WriteString(s[i : end+open])
				i = end + open
				continue
			}
			// No closing run — not a span. Emit the backticks and keep going.
			b.WriteString(s[i : i+open])
			i += open
			continue
		}

		if s[i] == '<' {
			if m := placeholderRE.FindString(s[i:]); m != "" {
				b.WriteByte('`')
				b.WriteString(m)
				b.WriteByte('`')
				i += len(m)
				continue
			}
			b.WriteString("&lt;")
			i++
			continue
		}

		if s[i] == '>' {
			b.WriteString("&gt;")
			i++
			continue
		}

		b.WriteByte(s[i])
		i++
	}

	return b.String()
}

// Cell is Prepare plus the table-cell escaping: a literal `|` would end the
// cell early, and an embedded newline would end the row.
func Cell(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.ReplaceAll(Prepare(s), "|", `\|`)
}

// backtickRun returns the length of the run of backticks starting at i.
func backtickRun(s string, i int) int {
	n := 0
	for i+n < len(s) && s[i+n] == '`' {
		n++
	}
	return n
}

// closingRun returns the index of the run of exactly n backticks that closes a
// span opened before position from, or -1 if there is none.
func closingRun(s string, from, n int) int {
	for i := from; i < len(s); {
		if s[i] != '`' {
			i++
			continue
		}
		run := backtickRun(s, i)
		if run == n {
			return i
		}
		i += run
	}
	return -1
}
