name: Spellcheck
on:
  pull_request:
    paths:
      - 'book/src/**/*.md'
      - 'docs/**/*.md'
      - '**/*.go'
jobs:
  spell:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v7
      - uses: streetsidesoftware/cspell-action@v8
        with:
          config: cspell.json
          files: |
            book/src/**/*.md
            docs/**/*.md
